[package]
name = "egui_glass_demo"
version = "0.1.0"
edition = "2021"
rust-version = "1.92"
license = "MIT"
publish = false

[dependencies]
egui = { workspace = true }
eframe = { workspace = true }
egui_glass = { path = "../../crates/egui_glass", features = ["serde"] }
image = { workspace = true }
log = "0.4"
serde = { workspace = true }
serde_json = { workspace = true }
rfd = { workspace = true }

[dev-dependencies]
pollster = "0.4"
